### ISSUE TITLE
finer grained zooming - manual plate solving

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#3013]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to compare Stellarium output to real images -  a kind of "manual plate solving".
For this it is important to be able to select a precise zoom factor + (added:) rotation angle.

![image](https://user-images.githubusercontent.com/3529789/213921989-46d0b953-8893-4505-89e7-f5638d0a2dc0.png)

![image](https://user-images.githubusercontent.com/3529789/213921411-22fcac81-0fa2-4a14-b1d9-8f66443e89a4.png)
(Source: https://www.facebook.com/groups/sterrenkundeforumVVS/posts/1958468424356632/)

This shows a small offset between computed and actual position (in this case probably about 1 arcmin).
Such an offset can be expected, nevertheless it gives an indication of precision.

The problem is that I cannot accurately select a scale so that image and viewport coincide sufficiently, because there is no way to select fractional zoom levels. As a result, there is a significant scale difference on the right side of the images.

**Describe the solution you'd like**
A text box that allows to enter a more precise zoom/scale level; or, some way to expand the viewport with the mouse (e.g. ctrl-drag).

**Describe alternatives you've considered**
Approximation.

**Additional context**

**Comment by 10110111** [comment]
Indeed, it would be quite useful. I'm currently using my laptop's touchpad for this, because it sends finer scroll events, but this is very hard to use, because it requires very precise motion of the fingers.

**Comment by gzotti** [comment]
You can preconfigure 10 fov settings to hotkeys.

**Comment by axd1967** [comment]
> You can preconfigure 10 fov settings to hotkeys.

But these are fixed settings. I need e.g. 0.12 degrees FOV)

**Comment by alex-w** [comment]
> > You can preconfigure 10 fov settings to hotkeys.
> 
> But these are fixed settings. I need e.g. 0.12 degrees FOV)

Wrong statement. We provide some collection of FOV, but all of them can be redefined via config.ini file

**Comment by 10110111** [comment]
OK, `fov/quick_fov_0` to `fov/quick_fov_9` should work I suppose, just as the `--fov` command-line option. This is better than nothing, but it still doesn't let one easily set a custom FoV on the fly (need to restart after changing `config.ini`).

**Comment by gzotti** [comment]
I would just work with e.g. 0.5° (or 0.25°, or 0.2°, I hope you get the point) plus Oculars plugin to simulate my sensor frame.

**Comment by axd1967** [comment]
> I would just work with e.g. 0.5° (or 0.25°, or 0.2°, I hope you get the point) plus Oculars plugin to simulate my sensor frame.

Actually that is not so bad as workaround!

But for this purpose, the user would want to disable the FOV outline, the mask, etc. This is not very practical, compared to adding a zoom mechanism.

**Comment by gzotti** [comment]
The sensor view in the Oculars plugin was designed for exposure planning and analysis. If you don't want to use the dedicated tool, you must find alternatives like redefining one of the fixed fov shortcuts.

Why would a user want to disable the sensor frame when analysing the photo? It also allows setting slight rotations that cannot be applied to the screen. The zoom is independent. If I would use it, I would probably define a custom fov 15-25% larger than my sensor frame plus use the Oculars sensor view. Or just use entirely different software.

One telescope/sensor combination may require one custom fov setting. Just as buying a telescope or CCD is rarely done on the fly, an occasional edit in a documented location is not seen as unacceptable burden.

**Comment by axd1967** [comment]
Good input about the rotation! I've added it to the requirements.

The sensor frame rotation feature is inadequate for this issue because the requirement is to rotate the **viewport** (i.e. the entire screen), not the sensor rectangle.

A workaround could be to find a fictional location that provides the correct orientation of the Stellarium viewport... (Because even the equatorial mount mode might not be sufficient to alleviate rotation issues.)

Note that in this use case, the comparison is done by alt-tabbing between a full-screen display of the image, and a full-screen Stellarium.

(Ideally, it would be very nice to be able to import an image and rotate it as desired ;-) )

**Comment by alex-w** [comment]
This is a full inadequate requirements, so, please solve it yourself.

**Comment by gzotti** [comment]
We have no plans to support this feature in the foreseeable future. There is other software for that.

**Comment by axd1967** [comment]
There we go again. A perfectly reasonable feature that is not urgent, is confirmed by a different user. 

This is a good first issue for a keen developer and belongs in the backlog, because the **closed** status will mask this issue for new developers.

[for_wishlist](https://github.com/Stellarium/stellarium/search?q=for_wishlist&type=issues)
