### ISSUE TITLE
No label for the Sun

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#4076]
It appears the label for the Sun has vanished. See the screenshot below:

![bild](https://github.com/user-attachments/assets/5b32357d-b264-46bd-8cc4-c72599c7807a)

Current master, built with Qt6.7.1 on Windows 10.

None of the skycultures show a label for the Sun.

**Comment by henrysky** [comment]
My PR #4023 has introduced this bug by introducing the Sun barycentric position...

**Comment by henrysky** [comment]
The label shows up when you zoomed in, but not zoom out with very large field of view.

**Comment by alex-w** [comment]
> The label shows up when you zoomed in, but not zoom out with very large field of view.

But... FOV = 235 degrees

![stellarium-005](https://github.com/user-attachments/assets/8fa3c239-5f78-49b1-98df-14f9645cc993)

**Comment by alex-w** [comment]
@Atque are you using macOS?

**Comment by alex-w** [comment]
> I think you also need to use a JPL emphem because I have assumed barycenter==heliocenter if not loading JPL emphem.

Yes! Plus sometimes I see a freeze now when JPL DExxx is disabling

**Comment by henrysky** [comment]
> > I think you also need to use a JPL emphem because I have assumed barycenter==heliocenter if not loading JPL emphem.
> 
> Yes! Plus sometimes I see a freeze now when JPL DExxx is disabling
> 
> P.S. Jumping the Sun position when VSOP/DE switching looks no very good - probably more bugs here :(

I have just pushed a commit that should have fixed the Sun jumping position VSOP/DE switching.

**Comment by alex-w** [comment]
@henrysky Hmm... I'm still see freezing sometimes and I see sometimes "jumping" of Venus (at least a name of the planet) when JPL DExxx is used. Would be you check the fix again?

**Comment by henrysky** [comment]
The jumping of venus happen by itself or switching JPL DExxx on and off? I Don't think I am seeing any freezing or planet label issue.

**Comment by alex-w** [comment]
The jumping of Venus (and other planets :( ) happens by itself immediately before freezing when JPL DExxx is using.

**Comment by henrysky** [comment]
Is the freezing occassional and very noticeable? I still Don't see any issue on my laptop.

**Comment by alex-w** [comment]
> Is the freezing occassional and very noticeable? I still Don't see any issue on my laptop.

Yes, it's very noticeable (a pre-crash state?) I'll check it under GDB tonight.

**Comment by alex-w** [comment]
> Is the freezing occassional and very noticeable? I still Don't see any issue on my laptop.

Please see a short video for jumping planets (sorry for Russian language):
https://github.com/user-attachments/assets/95ed49ad-5ba2-4649-abb4-8407f7cf7d1b

A crash is fixed currently (it was in refractionexcintion class)

**Comment by alex-w** [comment]
> I still cant reproduce the issue on a MacOS 15.2 or Windows 11 24H2 with Nvidia GPU with the current `master` branch🤔. Maybe this is a Linux specific issue?

It's interesting - I can't reproduce the issue on Windows too! @10110111 would you check it on your linux?

**Comment by 10110111** [comment]
> would you check it on your linux?

Do you mean the blinking of the planets as in your video? No, I don't reproduce it on Ubuntu 20.04, neither with DE440 enabled nor with it disabled.

**Comment by alex-w** [comment]
> > would you check it on your linux?
> 
> Do you mean the blinking of the planets as in your video? No, I don't reproduce it on Ubuntu 20.04, neither with DE440 enabled nor with it disabled.

Yes. Well, looks like this is a problem on my side O_o

**Comment by 10110111** [comment]
Or you could share your config file, I'd try it.

**Comment by alex-w** [comment]
> Or you could share your config file, I'd try it.

Please remove `.txt`: [config.ini.txt](https://github.com/user-attachments/files/18515234/config.ini.txt)

**Comment by 10110111** [comment]
Well, with your config there are no jumps too.

**Comment by alex-w** [comment]
> Well, with your config there are no jumps too.

OK
