### ISSUE TITLE
Double (mirrored) ephemeris lines in perspective/orthographic projections

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#811]
### Expected Behaviour
Ephemeris lines display as normal, even when using perspective and orthographic projections.

### Actual Behaviour
Lines show up in doubles, or "mirrored". That is, a mirrored version of the line is displayed in the opposite direction of the real line. It's not attached to the sky and floats around when panning. See this screenshot:

![stellarium-240](https://user-images.githubusercontent.com/37028368/67325823-ff6d9200-f515-11e9-881a-c7aacd0480c3.png)

The mirrored line (note that it has neither markers nor lables) is located between Jupiter and Venus. This screenshot uses perspective projection, and the same result is seen when using orthographic projection. The rest of them are fine.

### Steps to reproduce
1. Show an ephemeris of a planet/asteroid/comet of choice.
2. Show lines.
3. Look in the opposite direction of the true ephemeris line.

### System
* Stellarium version: stellarium-0.19.2.17267-win64.exe (latest public beta)
* Operating system: Windows 10 64-bit
* Graphics Card: GeForce GTX 1070, latest drivers

**Comment by alex-w** [comment]
Same problem for planetary trails!

**Comment by guillaumechereau** [comment]
I just pushed a fix attempt in a branch: fix-ephemeris-lines-perspective.

**Comment by alex-w** [comment]
I've tested it and apparently it solve the bug, because I don't see rendering issue now.

**Comment by alex-w** [comment]
Oops... drawing in orthographic projection still have problem

**Comment by guillaumechereau** [comment]
I push a fix for the orthographic projection.  This is not a perfect solution: it might still shows some errors at the border, but I think it should be enough for the moment.
